### ISSUE TITLE
 No such file or directory: '/content/deep-text-recognition-benchmark/log_demo_result.txt'

### ISSUE THREAD

**Issue by JiahaoXU9** [ahmed-nady/Sports-Player-Identification#1]
Hi I ran your code on jupyter notebook but it seems it lack one file

**Comment by ahmed-nady** [comment]
This file is created automatically each time you run the code. The content of this file is the image path and text that exits in the image and its confidence. If this is still a problem with you, you could change the path of this file which is located in 
line **70** "**log = open(f'./log_demo_result.txt', 'w')**" **in demo.py in deep-text-recognition-benchmark folder**

**Comment by ahmed-nady** [comment]
Try to run online first and then make sure you use the detection code from this repository ( https://github.com/ahmed-nady/keras-ocr.git). Also, you can back to the code keras_ocr/detection.py line 700 where the detector class is defined
